### ISSUE TITLE
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0) sleeping for 216.0 secs

### ISSUE THREAD

**Issue by ArthurMorgan-2023** [krisbolton/twint-in-jupyter#1]
getting this error.. how to resolve it..

**Comment by krisbolton** [comment]
Hi, I'll take a look later on today. However, I assume this will be an issue caused by Elon Musk's changes. Twitter has made some API changes recently. Twitter will also be placing the API behind a paywall, and I imagine the developer of TWINT won't be paying as its a small open source project. So this repo and others using it will cease to function. It's a real shame!
